#!/bin/sh

# KEY DEFINITIONS TO REMEMBER

# $Mod = WINDOWS key or Super key or Mod4
# Mod1 = ALT key
# Control = CTRL key
# Shift = SHIFT key
# Escape = ESCAPE key
# Return = ENTER or RETURN key
# KP_Enter = Keypad Enter
# Pause = PAUSE key
# Print = PRINT key
# Tab = TAB key
set $myTerm kitty
font pango:Hack 12

#Set Alt key
#set $mod Mod1

#set Super key
set $mod Mod4

set $up j
set $down k
set $left h
set $right l

################# Single and Dual screen #################

exec --no-startup-id xrandr --output DP-2 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output DP-0 --mode 2560x1440 --pos 2560x0 --rotate right

# Current setup

set $firstMonitor DP-2
set $secondMonitor DP-0

workspace 1 output $firstMonitor
workspace 2 output $secondMonitor
workspace 3 output $firstMonitor
workspace 4 output $secondMonitor
workspace 5 output $firstMonitor
workspace 6 output $secondMonitor
workspace 7 output $firstMonitor
workspace 8 output $secondMonitor
workspace 9 output $firstMonitor
workspace 10 output $secondMonitor

# switch to workspace
bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace 1; workspace 1
bindsym $mod+Shift+2 move container to workspace 2; workspace 2
bindsym $mod+Shift+3 move container to workspace 3; workspace 3
bindsym $mod+Shift+4 move container to workspace 4; workspace 4
bindsym $mod+Shift+5 move container to workspace 5; workspace 5
bindsym $mod+Shift+6 move container to workspace 6; workspace 6
bindsym $mod+Shift+7 move container to workspace 7; workspace 7
bindsym $mod+Shift+8 move container to workspace 8; workspace 8
bindsym $mod+Shift+9 move container to workspace 9; workspace 9
bindsym $mod+Shift+0 move container to workspace 10; workspace 10

# move  container to workspace
bindsym Control+1 move container to workspace 1
bindsym Control+2 move container to workspace 2
bindsym Control+3 move container to workspace 3
bindsym Control+4 move container to workspace 4
bindsym Control+5 move container to workspace 5
bindsym Control+6 move container to workspace 6
bindsym Control+7 move container to workspace 7
bindsym Control+8 move container to workspace 8
bindsym Control+9 move container to workspace 9
bindsym Control+0 move container to workspace 10

# read 1 character and mark the current window with this character
bindsym $mod+m exec i3-input -F 'mark %s' -l 1 -P 'Mark: '

# read 1 character and go to the window with the character
bindsym $mod+g exec i3-input -F '[con_mark="%s"] focus' -l 1 -P 'Goto: '

bindsym $mod+p exec i3-input -F 'rename workspace to "%s"' -P 'New name: '
bindsym $mod+F1 [class="firefox"] focus
bindsym $mod+F2 [class="firefox"] move workspace current
bindsym $mod+F3 [class="firefox"] move workspace back_and_forth
workspace_auto_back_and_forth yes

################# 3 menu's #################

# start dmenu
bindsym $mod+shift+d exec --no-startup-id dmenu_run -i -nb '#191919' -nf '#fea63c' -sb '#fea63c' -sf '#191919' -fn 'NotoMonoRegular:bold:pixelsize=14'
# Rofi - show open windows
bindsym $mod+w exec --no-startup-id rofi -modi window -config ~/.config/rofi/config -show window
# start xfce-appfinder
bindsym mod1+F3 exec --no-startup-id xfce4-appfinder
# start rofi small
bindsym $mod+r exec --no-startup-id rofi -show run
# start rofi sidebar
bindsym $mod+c exec --no-startup-id rofi -config ~/.config/rofi/config.sidebar.rasi -show drun
# ArcoLinux Logout
bindsym $mod+X exec --no-startup-id archlinux-logout
# Finder
bindsym Control+mod1+k exec --no-startup-id rofi -config ~/.config/rofi/config.sidebar2.rasi -show find -modi find:~/.local/share/rofi/finder.sh
bindsym Control+Tab exec --no-startup-id ~/.bin/at.sh
bindsym Control+mod1+s exec --no-startup-id ~/.bin/dmenu_hist.sh
bindsym Control+mod1+m exec --no-startup-id ~/.bin/dmenu_man.sh

# restart i3 inplace
bindsym $mod+Shift+r restart
# reload the configuration file
bindsym $mod+Shift+c reload
# kill focused window
bindsym $mod+q kill
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

################# Moving around in i3 #################

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Right focus right
bindsym $mod+Up focus up

# move focused window
bindsym $mod+Shift+$left move left
bindsym $mod+Shift+$down move down
bindsym $mod+Shift+$up move up
bindsym $mod+Shift+$right move right
bindsym mod1+control+a move container to workspace back_and_forth; workspace back_and_forth

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# next/previous workspace
workspace_auto_back_and_forth yes
bindsym mod1+Tab workspace next
bindsym mod1+q exec --no-startup-id skippy-xd --activate-window-picker
bindsym $mod+Tab workspace back_and_forth

#navigate workspaces next / previous
bindsym mod1+Control+Right workspace next
bindsym mod1+Control+Left workspace prev
bindsym mod1+Control+$right workspace next
bindsym mod1+Control+$left workspace prev

# switch to workspace with urgent window automatically
for_window [urgent=latest] focus

################# Tiling parameters #################

# orientation for new workspaces
default_orientation horizontal

#bindsym $mod+Control+h split horizontal
#bindsym $mod+Control+v split vertical
bindsym $mod+Control+h split h;exec notify-send 'tile horizontally'
bindsym $mod+Control+v split v;exec notify-send 'tile vertically'
bindsym $mod+Control+q split toggle

bindsym $mod+f fullscreen toggle

bindsym $mod+s layout stacking
bindsym $mod+z layout tabbed
bindsym $mod+d layout toggle split

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+c focus child

################# assign applications to workspaces #################

# Assign application to start on a specific workspace
# you can find the class with xprop

# Workspace 1
assign [class="Firefox"]										                    → 1
assign [class="Geany"] 								                                → 1
#assign [class="Pcmanfm"]													        → 1
#assign [class="Thunar"]														    → 1

# Workspace 2 
assign [class="Chromium"]                                       				    → 3
assign [class="Pcmanfm"]													        → 3
assign [class="Notepadqq"]						                                    → 3

# Workspace 3 Inkscape
#assign [class="Inkscape"]                                                          → 4

# Workspace 4 Gimp
#assign [class="Gimp"]                                                              → 4

# Workspace 5 Images and meld
#assign [class="ristretto|Ristretto|shotwell|Shotwell|Xviewer|Nitrogen"]            → 5
#assign [class="feh|gthumb|Gthumb|eog|Eog|Pinta|pixeluvo|Pixeluvo"]                 → 5
#assign [class="Meld"]                                                              → 5
assign [class="Gimp"]                                                               → 5

# Workspace 6 all video related software
#assign [class="Vlc|vlc"]                                                           → 6

# Workspace 7 virtual machines and settings
assign [class="Vmplayer|VirtualBox"]						    					→ 7

# Workspace 8 file managers
#assign [class="Nemo|Thunar|Caja|nautilus|Nautilus"]                                → 8

# Workspace 9 Video related
#assign [class="smplayer|vlc"]	                                                    → 9

# Workspace 10 music related
assign [class="Spotify|spotify"]                                                    → 10
assign [class="Audacious|audacious"]                                                → 10
#fix for spotify not moving to workspace 10
#for_window [class="Audacious"] move to workspace 10

################# execute applications at boot #################
# USER APPLICATIONS TO START AT BOOT

# Autotiling
exec_always --no-startup-id autotiling

exec --no-startup-id setxkbmap -layout us,bg -variant ,phonetic -option grp:alt_shift_toggle
exec_always --no-startup-id numlockx on &
exec_always --no-startup-id . ~/bashrc
exec --no-startup-id pgrep urxvtd 2> /dev/null || urxvtd -q -o -f &
exec --no-startup-id xrdb -merge ~/.Xresources &
exec --no-startup-id xset b off
exec_always --no-startup-id picom -b --vsync-use-glfinish --experimental-backends --config ~/picom.NGC &
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec --no-startup-id dunst &
exec --no-startup-id xfce4-power-manager --daemon &
exec --no-startup-id nm-applet &
exec --no-startup-id volumeicon &
exec --no-startup-id /home/ngc/.bin/nitro-i3.sh
exec --no-startup-id /home/ngc/.bin/i3-startup.sh
exec --no-startup-id /usr/bin/autocutsel & 
#exec_always --no-startup-id nice polybar -c /home/ngc/.config/polybar/new-polybar mainbar-i3 >>/tmp/polybar_i3.log 2>&1 & disown
#exec_always ~/.config/polybar/launch.sh
exec_always --no-startup-id /usr/bin/xsct 6000 1>/dev/null &
#exec_always --no-startup-id skippy-xd --start-daemon 2&>1 & disown

################# keyboard shortcuts #################

bindsym $mod+Return exec $MyTerm;focus
bindsym $mod+t exec urxvtc;focus
bindsym $mod+e exec thunar;focus
bindsym $mod+KP_Enter exec $MyTerm;focus
bindsym F12 exec --no-startup-id xfce4-terminal --drop-down; focus

bindsym control+mod1+f exec --no-startup-id firefox;focus
bindsym control+mod1+g exec --no-startup-id geany;focus
bindsym control+mod1+c exec --no-startup-id chromium;focus
bindsym control+mod1+w exec --no-startup-id dmenufm;focus
bindsym control+mod1+e exec --no-startup-id pcmanfm;focus
bindsym control+mod1+b exec --no-startup-id luakit;focus
bindsym control+mod1+i exec --no-startup-id ~/.bin/dm_search.sh

bindsym control+mod1+o exec --no-startup-id ~/.bin/picom-toggle.sh

for_window [class="Urxvt"] focus
for_window [class="Kitty"] focus
for_window [class="Uxterm"] focus
for_window [class="Audacious"] focus

# bar toggle, hide or show
bindsym $mod+b bar mode toggle

################# screenshots #################

bindsym Print exec --no-startup-id scrot 'ArcoLinux-%Y-%m-%d-%s_screenshot_$wx$h.jpg' -e 'mv $f $$(xdg-user-dir PICTURES)'
bindsym Control+Print exec --no-startup-id xfce4-screenshooter
bindsym Control+Shift+Print exec --no-startup-id gnome-screenshot -i
#bindsym shift+Print exec --no-startup-id shutter

################# floating or tiled #################

#floating enabled from some programs - find with xprop

for_window [class="Arcolinux-welcome-app.py"] floating enable
for_window [class="Arcolinux-tweak-tool.py"] floating enable
for_window [class="Orage"] floating enable
for_window [class="Bleachbit"] floating disable
for_window [class="Blueberry.py"] floating enable
for_window [class="Brasero"] floating disable
for_window [class="Galculator"] floating enable
for_window [class="Gnome-disks"] floating disable
for_window [class="^Gnome-font-viewer$"] floating enable
for_window [class="^Gpick$"] floating enable
for_window [class="Hexchat"] floating disable
for_window [class="Imagewriter"] floating enable
for_window [class="Font-manager"] floating enable
for_window [class="Lxappearance"] floating enable
for_window [class="Nitrogen"] floating disable
for_window [class="Pavucontrol"] floating disable
for_window [class="Peek"] floating enable
for_window [class="^Skype$"] floating enable
for_window [class="System-config-printer.py"] floating enable
for_window [class="Unetbootin.elf"] floating enable
for_window [class="Usb-creator-gtk"] floating enable
for_window [class="^Vlc$"] floating disable
for_window [class="Wine"] floating disable
for_window [class="Xfburn"] floating disable
for_window [class="Xfce4-appfinder"] floating enable
for_window [class="Xfce4-settings-manager"] floating disable
for_window [class="Xfce4-taskmanager"] floating enable
for_window [instance="gimp"] floating disable
for_window [instance="script-fu"] border normal
for_window [instance="variety"] floating disable
for_window [title="Copying"] floating enable
for_window [title="Deleting"] floating enable
for_window [title="Moving"] floating enable
for_window [window_role="^gimp-toolbox-color-dialog$"] floating enable
for_window [window_role="pop-up"] floating enable
for_window [window_role="^Preferences$"] floating enable
for_window [window_role="setup"] floating enable

################# audio settings #################

bindsym XF86AudioRaiseVolume exec --no-startup-id "amixer -D pulse sset Master '5%+'"
bindsym XF86AudioLowerVolume exec --no-startup-id "amixer -D pulse sset Master '5%-'"
bindsym XF86AudioMute exec --no-startup-id "amixer -D pulse set Master toggle"
bindsym XF86AudioPlay exec --no-startup-id playerctl play-pause
bindsym XF86AudioNext exec --no-startup-id playerctl next
bindsym XF86AudioPrev exec --no-startup-id playerctl previous
bindsym XF86AudioStop exec --no-startup-id playerctl stop

#Popups during fullscreen mode
popup_during_fullscreen smart

################# borders #################
#hide_edge_borders both
bindsym $mod+shift+b exec --no-startup-id i3-msg border toggle

#changing border style
bindsym $mod+i border normal
bindsym $mod+y border 1pixel
bindsym $mod+u border none

default_border pixel 2
default_floating_border pixel 2
for_window [class="Orage"] border pixel 0

################# i3 gaps #################

#for_window [class="^.*"] border pixel 2
gaps inner 10
gaps outer 5
#smart_gaps on
#smart_borders on

# i3 gaps change  

set $mode_gaps Gaps: (o) outer, (i) inner
set $mode_gaps_outer Outer Gaps: +|-|0 (local), Shift + +|-|0 (global)
set $mode_gaps_inner Inner Gaps: +|-|0 (local), Shift + +|-|0 (global)

bindsym $mod+Shift+g mode "$mode_gaps"

mode "$mode_gaps" {
        bindsym o      mode "$mode_gaps_outer"
        bindsym i      mode "$mode_gaps_inner"
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

mode "$mode_gaps_inner" {
        bindsym plus  gaps inner current plus 5
        bindsym minus gaps inner current minus 5
        bindsym 0     gaps inner current set 0

        bindsym Shift+plus  gaps inner all plus 5
        bindsym Shift+minus gaps inner all minus 5
        bindsym Shift+0     gaps inner all set 0

        bindsym Return mode "default"
        bindsym Escape mode "default"
}
mode "$mode_gaps_outer" {
        bindsym plus  gaps outer current plus 5
        bindsym minus gaps outer current minus 5
        bindsym 0     gaps outer current set 0

        bindsym Shift+plus  gaps outer all plus 5
        bindsym Shift+minus gaps outer all minus 5
        bindsym Shift+0     gaps outer all set 0

        bindsym Return mode "default"
        bindsym Escape mode "default"
}

################# Modes #################

#Press ctrl+alt+x - check toolbar for next choices
bindsym control+mod1+X mode "$mode_system"

set $mode_system System (k) lock, (l) logout, (u) suspend, (h) hibernate, (r) reboot, (s) shutdown
mode "$mode_system" {
    bindsym k exec --no-startup-id ~/.config/i3/scripts/i3exit.sh lock, mode "default"
    bindsym l exec --no-startup-id ~/.config/i3/scripts/i3exit.sh logout, mode "default"
    bindsym u exec --no-startup-id ~/.config/i3/scripts/i3exit.sh suspend, mode "default"
    bindsym h exec --no-startup-id ~/.config/i3/scripts/i3exit.sh hibernate, mode "default"
    bindsym r exec --no-startup-id ~/.config/i3/scripts/i3exit.sh reboot, mode "default"
    bindsym s exec --no-startup-id ~/.config/i3/scripts/i3exit.sh shutdown, mode "default"

    # back to normal: Enter or Escape
    bindsym Return mode "default"
    bindsym Escape mode "default"
}

# resize window (you can also use the mouse for that)
bindsym $mod+Control+r mode "resize"

mode "resize" {
        
        bindsym $left       resize shrink width 10 px or 10 ppt
        bindsym $down       resize grow height 10 px or 10 ppt
        bindsym $up         resize shrink height 10 px or 10 ppt
        bindsym $right      resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left        resize grow width 10 px or 10 ppt
        bindsym Down        resize grow height 10 px or 10 ppt
        bindsym Up          resize shrink height 10 px or 10 ppt
        bindsym Right       resize shrink width 10 px or 10 ppt

        # back to normal: Enter or Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

bindsym control+mod1+r mode "$mode_autorandr"

set $mode_autorandr Autorandr (d)ocked, (m)obile, (b)oth
mode "$mode_autorandr"  {
        bindsym d exec --no-startup-id autorandr -l docked, mode "default"        
        bindsym m exec --no-startup-id autorandr -l mobile, mode "default"         
        bindsym b exec --no-startup-id autorandr -l both, mode "default"
        #exit resize mode: Enter or Escape         
        bindsym Return mode "default"         
        bindsym Escape mode "default"   
}

################# bar #################

bar {

	bindsym button3 exec --no-startup-id jgmenu_run
    #height 26
    #workspace_buttons yes
    font pango:DejaVu Sans Mono, FontAwesome 11

    position top

    #system icons
    #tray_output none
    tray_output $firstMonitor
    #tray_output $secondMonitor

    # OPTION 1 : i3status
    #status_command i3status
    #status_command i3status -c ~/.config/i3/i3status.conf
	status_command /usr/bin/i3status-rs /home/ngc/.config/i3status-rust/config.toml
	
    # OPTION 2 : i3blocks
    #status_command i3blocks
    #status_command i3blocks -c ~/.config/i3/i3blocks.conf
    #status_command i3blocks -c ~/.config/i3/i3blocks-rainbow.conf
    #status_command i3blocks -c ~/.config/i3/i3blocks-original.conf
    #status_command i3blocks -c ~/.config/i3/i3blocks-awesome.conf

    ## OPTION 3 : conky
    #status_command ~/.config/i3/start-conky-i3statusbar.sh

    # i3 bar colors
    # variable border background Text

    colors {
        #background #3B4252
        background #2C3A4E
        statusline #eeeeee
        separator  #666666

        ### colorclass		border  backgr. text
        focused_workspace	#a9a9a9 #F08080 #000000
        active_workspace	#a9a9a9 #74CEB8 #646CF2
        inactive_workspace	#a9a9a9 #2C3A4E #FFFFFF
        urgent_workspace	#a9a9a9 #d42121 #FFFFFF
        binding_mode		#2f343a #900000 #ffffff
        }

    }

    # Window color settings
    # class                 border  backgr. text    indicator child_border
    client.focused          #F08080 #F08080 #e5e5e5 #6790EB 
    client.unfocused        #222222 #6790EB #aaaaaa #222222  
    client.focused_inactive #222222 #222222 #a9a9a9 #222222
    client.placeholder      #222222 #222222 #aaaaaa #222222
    client.urgent           #CC4E4E #CC4E4E #f7f7f7 #CC4E4E

    client.background       #242424

################# mouse settings #################

# mouse settings
# The middle button over a titlebar kills the window
# bindsym --release button2 kill

# The middle button and a modifer over any part of the window kills the window
bindsym --whole-window $mod+button2 kill

# Resize with the right button 
bindsym --whole-window $mod+button4 floating toggle
#bindsym --whole-window $mod+button5

