#!/usr/bin/sh

# My aliases

alias la='ls -a'
alias ll='exa -alh -s name --group-directories-first --octal-permissions --icons'
alias l='ls -l'
alias l.="ls -A | egrep '^\.'"
alias lld='ls -lFahdo'
alias lsd='ls -d *'

alias less="less -iMFceqRSX -x2"
alias sensors='sysctl hw.sensors'
alias cls='echo -ne "\033c"'
alias mkdir='mkdir -p'
alias m="mcedit"
alias v="vim"
alias n="nano"
#alias less='less.sh'
export PAGER="most"
alias da='date "+%A, %B %d, %Y [%T]"'
#alias man="man -H"
alias lsof='fstat'
alias eg='egrep -i'
alias grep='grep -i'
alias h='fc -l'
alias portaudit='/usr/sbin/pkg audit -F'
alias svim="doas vim"
alias svi="doas vi"

#fix obvious typo's
alias cd..='cd ..'
alias pdw="pwd"
alias ..='cd ..'
alias ...='cd ...'

#readable output
alias df='df -h'
alias du='du -ch'
alias weather='curl http://wttr.in/Sofia'

#free
alias free="top -d1 | head -n 6"

#continue download
alias wget="wget -c"

#merge new settings
alias merge="xrdb -merge ~/.Xresources"

# Aliases for software managment
alias pkga='doas pkg_add -ivV'
alias pkgq='doas pkg_info -Q'
alias pkgi='doas pkg_info'
alias pkg_check='pkg_libchk'
alias pkg_locate="echo /usr/ports/*/*|tr ' ' '\n'"
alias update='doas pkg_add -u'

#ps
alias psa="ps aux"
alias psgrep="ps aux | grep -v grep | grep -i -e VSZ -e"

#shutdown or reboot
alias dsn="doas shutdown now"
alias dr="doas reboot"

#give the list of all installed desktops - xsessions desktops
alias xd="bat /home/ngc/.xsession"

# # ex = EXtractor for all kinds of archives
# # usage: ex <file>
ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.deb)       ar x $1      ;;
      *.tar.xz)    tar xf $1    ;;
      *.tar.zst)   tar xf $1    ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# vim:nospell:ft=sh:
